# Generated by Django 5.1.2 on 2024-10-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_proveedor_router'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='router',
            new_name='router_id',
        ),
    ]
